// Code generated by MockGen. DO NOT EDIT.
// Source: inssqs.go
//
// Generated by this command:
//
//	mockgen --source=inssqs.go
//
// Package mock_inssqs is a generated GoMock package.
package inssqs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// DeleteMessageBatch mocks base method.
func (m *MockInterface) DeleteMessageBatch(entries []SQSDeleteMessageEntry) ([]SQSDeleteMessageEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageBatch", entries)
	ret0, _ := ret[0].([]SQSDeleteMessageEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessageBatch indicates an expected call of DeleteMessageBatch.
func (mr *MockInterfaceMockRecorder) DeleteMessageBatch(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageBatch", reflect.TypeOf((*MockInterface)(nil).DeleteMessageBatch), entries)
}

// SendMessageBatch mocks base method.
func (m *MockInterface) SendMessageBatch(entries []SQSMessageEntry) ([]SQSMessageEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageBatch", entries)
	ret0, _ := ret[0].([]SQSMessageEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessageBatch indicates an expected call of SendMessageBatch.
func (mr *MockInterfaceMockRecorder) SendMessageBatch(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageBatch", reflect.TypeOf((*MockInterface)(nil).SendMessageBatch), entries)
}
