// Code generated by MockGen. DO NOT EDIT.
// Source: ./insrequester/requester.go

// Package insrequester is a generated GoMock package.
package insrequester

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRequester is a mock of Requester interface.
type MockRequester struct {
	ctrl     *gomock.Controller
	recorder *MockRequesterMockRecorder
}

// MockRequesterMockRecorder is the mock recorder for MockRequester.
type MockRequesterMockRecorder struct {
	mock *MockRequester
}

// NewMockRequester creates a new mock instance.
func NewMockRequester(ctrl *gomock.Controller) *MockRequester {
	mock := &MockRequester{ctrl: ctrl}
	mock.recorder = &MockRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequester) EXPECT() *MockRequesterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRequester) Delete(ctx context.Context, re RequestEntity) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, re)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRequesterMockRecorder) Delete(ctx, re interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRequester)(nil).Delete), ctx, re)
}

// Get mocks base method.
func (m *MockRequester) Get(ctx context.Context, re RequestEntity) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, re)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRequesterMockRecorder) Get(ctx, re interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRequester)(nil).Get), ctx, re)
}

// Load mocks base method.
func (m *MockRequester) Load() *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*Request)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockRequesterMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRequester)(nil).Load))
}

// Post mocks base method.
func (m *MockRequester) Post(ctx context.Context, re RequestEntity) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, re)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockRequesterMockRecorder) Post(ctx, re interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockRequester)(nil).Post), ctx, re)
}

// Put mocks base method.
func (m *MockRequester) Put(ctx context.Context, re RequestEntity) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, re)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRequesterMockRecorder) Put(ctx, re interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRequester)(nil).Put), ctx, re)
}

// WithCircuitbreaker mocks base method.
func (m *MockRequester) WithCircuitbreaker(config CircuitBreakerConfig) *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCircuitbreaker", config)
	ret0, _ := ret[0].(*Request)
	return ret0
}

// WithCircuitbreaker indicates an expected call of WithCircuitbreaker.
func (mr *MockRequesterMockRecorder) WithCircuitbreaker(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCircuitbreaker", reflect.TypeOf((*MockRequester)(nil).WithCircuitbreaker), config)
}

// WithHTTPClient mocks base method.
func (m *MockRequester) WithHTTPClient(client *http.Client) *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithHTTPClient", client)
	ret0, _ := ret[0].(*Request)
	return ret0
}

// WithHTTPClient indicates an expected call of WithHTTPClient.
func (mr *MockRequesterMockRecorder) WithHTTPClient(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithHTTPClient", reflect.TypeOf((*MockRequester)(nil).WithHTTPClient), client)
}

// WithHeaders mocks base method.
func (m *MockRequester) WithHeaders(headers Headers) *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithHeaders", headers)
	ret0, _ := ret[0].(*Request)
	return ret0
}

// WithHeaders indicates an expected call of WithHeaders.
func (mr *MockRequesterMockRecorder) WithHeaders(headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithHeaders", reflect.TypeOf((*MockRequester)(nil).WithHeaders), headers)
}

// WithRetry mocks base method.
func (m *MockRequester) WithRetry(config RetryConfig) *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithRetry", config)
	ret0, _ := ret[0].(*Request)
	return ret0
}

// WithRetry indicates an expected call of WithRetry.
func (mr *MockRequesterMockRecorder) WithRetry(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithRetry", reflect.TypeOf((*MockRequester)(nil).WithRetry), config)
}

// WithTimeout mocks base method.
func (m *MockRequester) WithTimeout(timeout time.Duration) *Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", timeout)
	ret0, _ := ret[0].(*Request)
	return ret0
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockRequesterMockRecorder) WithTimeout(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockRequester)(nil).WithTimeout), timeout)
}
